/********************************************************************************
** Form generated from reading UI file 'MainWindow.ui'
**
** Created by: Qt User Interface Compiler version 5.9.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>
#include "QVTKWidget.h"

QT_BEGIN_NAMESPACE

class Ui_MainWindowForm
{
public:
    QAction *_startFlexxAction;
    QAction *_stopFlexxAction;
    QAction *_startRSAction;
    QAction *_stopRSAction;
    QAction *_getNumberOfBytesAction;
    QAction *_getCharAction;
    QAction *_getArrayAction;
    QAction *_controlMotorAction;
    QAction *_setConfidenceAction;
    QAction *_IterativeClosestPointAction;
    QAction *_openFileAction;
    QAction *_saveFileAction;
    QAction *_keepOneFrameAction;
    QAction *_keepContinueFrameAction;
    QAction *actionFeature;
    QAction *_autoScanAction;
    QWidget *centralWidget;
    QVTKWidget *_qvtkWidget;
    QTableWidget *_pointCloudTable;
    QTabWidget *_processingTabWidget;
    QWidget *_filterTab;
    QTabWidget *_filterTabWidget;
    QWidget *_voxelGridTab;
    QLabel *_voxelGridXLabel;
    QLabel *_voxelGridYLabel;
    QDoubleSpinBox *_voxelGridYSpinBox;
    QDoubleSpinBox *_voxelGridZSpinBox;
    QDoubleSpinBox *_voxelGridXSpinBox;
    QLabel *_voxelGridZLabel;
    QWidget *_boundingBoxTab;
    QDoubleSpinBox *_boundingBoxMinYSpinBox;
    QLabel *_boundingBoxZLabel;
    QDoubleSpinBox *_boundingBoxMinXSpinBox;
    QLabel *_boundingBoxXLabel;
    QDoubleSpinBox *_boundingBoxMinZSpinBox;
    QLabel *_boundingBoxYLabel;
    QDoubleSpinBox *_boundingBoxMaxXSpinBox;
    QDoubleSpinBox *_boundingBoxMaxZSpinBox;
    QDoubleSpinBox *_boundingBoxMaxYSpinBox;
    QLabel *_boundingBoxXShiftLabel;
    QLabel *_boundingBoxYShiftLabel;
    QLabel *_boundingBoxZShiftLabel;
    QPushButton *_filterProcessingButton;
    QWidget *_keypointTab;
    QTabWidget *_keypointTabWidget;
    QWidget *_sift3DTab;
    QLabel *_siftMinScaleLabel;
    QLabel *_siftNROctavesLabel;
    QLabel *_siftNRScalesPerOctaveLabel;
    QDoubleSpinBox *_siftMinScaleSpinBox;
    QLabel *_siftMinContrastLabel;
    QDoubleSpinBox *_siftMinContrastSpinBox;
    QSpinBox *_siftNROctavesSpinBox;
    QSpinBox *_siftNRScalesPerOctaveSpinBox;
    QWidget *_harris3DTab;
    QLabel *_harrisSetRadiusSearchLabel;
    QLabel *_harrisRadiusLabel;
    QDoubleSpinBox *_harrisRadiusSpinBox;
    QDoubleSpinBox *_harrisRadiusSearchSpinBox;
    QLabel *_harrisMethodLabel;
    QComboBox *_harrisMethodComboBox;
    QPushButton *_keypointProcessingButton;
    QWidget *_correspondencesTab;
    QTabWidget *_correspondencesTabWidget;
    QWidget *_fpfhTab;
    QLabel *_fpfhNormalRadiusLabel;
    QLabel *_fpfhdescriptorRadiusLabel;
    QDoubleSpinBox *_fpfhDescriptorRadiusSpinBox;
    QSpinBox *_fpfhCorrespondencesKSpinBox;
    QLabel *_fpfhCorrespondencesKLabel;
    QDoubleSpinBox *_fpfhNormalRadiusSpinBox;
    QLabel *_fpfhRejectorInlierThresholdLabel;
    QDoubleSpinBox *_fpfhRejectorInlierThresholdSpinBox;
    QWidget *_shotRGBTab;
    QLabel *_shotdescriptorRadiusLabel;
    QSpinBox *_shotCorrespondencesKSpinBox;
    QLabel *_shotNormalRadiusLabel;
    QDoubleSpinBox *_shotNormalRadiusSpinBox;
    QLabel *_shotCorrespondencesKLabel;
    QDoubleSpinBox *_shotDescriptorRadiusSpinBox;
    QDoubleSpinBox *_shotRejectorInlierThresholdSpinBox;
    QLabel *_shotRejectorInlierThresholdLabel;
    QWidget *_pfhTab;
    QLabel *_pfhdescriptorKSearchLabel;
    QSpinBox *_pfhCorrespondencesKSpinBox;
    QLabel *_pfhNormalRadiusLabel;
    QLabel *_pfhCorrespondencesKLabel;
    QDoubleSpinBox *_pfhNormalRadiusSpinBox;
    QSpinBox *_pfhDescriptorKSearchSpinBox;
    QDoubleSpinBox *_pfhRejectorInlierThresholdSpinBox;
    QLabel *_pfhRejectorInlierThresholdLabel;
    QWidget *_pfhrgbTab;
    QLabel *_pfhrgbRejectorInlierThresholdLabel;
    QDoubleSpinBox *_pfhrgbRejectorInlierThresholdSpinBox;
    QSpinBox *_pfhrgbDescriptorKSearchSpinBox;
    QLabel *_pfhrgbCorrespondencesKLabel;
    QDoubleSpinBox *_pfhrgbNormalRadiusSpinBox;
    QLabel *_pfhrgbdescriptorKSearchLabel;
    QLabel *_pfhrgbNormalRadiusLabel;
    QSpinBox *_pfhrgbCorrespondencesKSpinBox;
    QPushButton *_correspondencesProcessingButton;
    QWidget *_regestrationTab;
    QPushButton *_regestrationProcessingButton;
    QTabWidget *_regestrationTabWidget;
    QWidget *_icpTab;
    QLabel *_icpOutlierThresholdLabel;
    QLabel *_icpCorrespondenceDistanceLabel;
    QDoubleSpinBox *_icpCorrespondenceDistanceSpinBox;
    QLabel *_icpTransformationEpsilonLabel;
    QDoubleSpinBox *_icpOutlierThresholdSpinBox;
    QLabel *_icpMaxIterationsLabel;
    QSpinBox *_icpMaxIterationsSpinBox;
    QDoubleSpinBox *_icpTransformationEpsilonSpinBox;
    QWidget *_reconstructTab;
    QTabWidget *_reconstructTabWidget;
    QWidget *_greedyProjectionTab;
    QLabel *_greedyProjectionMuLabel;
    QLabel *_greedyProjectionSearchRadiusLabel;
    QDoubleSpinBox *_greedyProjectionSearchRadiusSpinBox;
    QLabel *_greedyProjectionMaxNearestNeighborsLabel;
    QDoubleSpinBox *_greedyProjectionMuSpinBox;
    QLabel *_greedyProjectionMaxSurfaceAngleLabel;
    QSpinBox *_greedyProjectionMaxNearestNeighborsSpinBox;
    QLabel *_greedyProjectionMinAngleLabel;
    QLabel *_greedyProjectionMaxAngleLabel;
    QSpinBox *_greedyProjectionMaxSurfaceAngleSpinBox;
    QSpinBox *_greedyProjectionMinAngleSpinBox;
    QSpinBox *_greedyProjectionMaxAngleSpinBox;
    QDoubleSpinBox *_greedyProjectNormalSearchRadiusSpinBox;
    QLabel *_GreedyProjectNormalSearchRadiusLabel;
    QWidget *_marchingCubesTab;
    QLabel *_marchingCubesGridResolutionXLabel;
    QLabel *_marchingCubesGridResolutionZLabel;
    QLabel *_marchingCubesGridResolutionYLabel;
    QSpinBox *_marchingCubesGridResolutionYSpinBox;
    QSpinBox *_marchingCubesGridResolutionXSpinBox;
    QSpinBox *_marchingCubesGridResolutionZSpinBox;
    QLabel *_marchingCubesIsoLevelLabel;
    QDoubleSpinBox *_marchingCubesIsoLevelSpinBox;
    QLabel *_marchingCubesNormalSearchRadiusLabel;
    QDoubleSpinBox *_marchingCubesNormalSearchRadiusSpinBox;
    QPushButton *_reconstructProcessingButton;
    QMenuBar *menuBar;
    QMenu *menuCamera;
    QMenu *menuPico_Flexx;
    QMenu *menuIntel_Realsense;
    QMenu *menuArduino;
    QMenu *menucommunicate;
    QMenu *menuControl_Motor;
    QMenu *menuFile;
    QMenu *menuPointCloud;
    QMenu *menuKeep_PointCloud;
    QMenu *menuScan;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindowForm)
    {
        if (MainWindowForm->objectName().isEmpty())
            MainWindowForm->setObjectName(QStringLiteral("MainWindowForm"));
        MainWindowForm->resize(1280, 850);
        _startFlexxAction = new QAction(MainWindowForm);
        _startFlexxAction->setObjectName(QStringLiteral("_startFlexxAction"));
        _stopFlexxAction = new QAction(MainWindowForm);
        _stopFlexxAction->setObjectName(QStringLiteral("_stopFlexxAction"));
        _startRSAction = new QAction(MainWindowForm);
        _startRSAction->setObjectName(QStringLiteral("_startRSAction"));
        _stopRSAction = new QAction(MainWindowForm);
        _stopRSAction->setObjectName(QStringLiteral("_stopRSAction"));
        _getNumberOfBytesAction = new QAction(MainWindowForm);
        _getNumberOfBytesAction->setObjectName(QStringLiteral("_getNumberOfBytesAction"));
        _getCharAction = new QAction(MainWindowForm);
        _getCharAction->setObjectName(QStringLiteral("_getCharAction"));
        _getArrayAction = new QAction(MainWindowForm);
        _getArrayAction->setObjectName(QStringLiteral("_getArrayAction"));
        _controlMotorAction = new QAction(MainWindowForm);
        _controlMotorAction->setObjectName(QStringLiteral("_controlMotorAction"));
        _setConfidenceAction = new QAction(MainWindowForm);
        _setConfidenceAction->setObjectName(QStringLiteral("_setConfidenceAction"));
        _IterativeClosestPointAction = new QAction(MainWindowForm);
        _IterativeClosestPointAction->setObjectName(QStringLiteral("_IterativeClosestPointAction"));
        _openFileAction = new QAction(MainWindowForm);
        _openFileAction->setObjectName(QStringLiteral("_openFileAction"));
        _saveFileAction = new QAction(MainWindowForm);
        _saveFileAction->setObjectName(QStringLiteral("_saveFileAction"));
        _keepOneFrameAction = new QAction(MainWindowForm);
        _keepOneFrameAction->setObjectName(QStringLiteral("_keepOneFrameAction"));
        _keepContinueFrameAction = new QAction(MainWindowForm);
        _keepContinueFrameAction->setObjectName(QStringLiteral("_keepContinueFrameAction"));
        actionFeature = new QAction(MainWindowForm);
        actionFeature->setObjectName(QStringLiteral("actionFeature"));
        _autoScanAction = new QAction(MainWindowForm);
        _autoScanAction->setObjectName(QStringLiteral("_autoScanAction"));
        centralWidget = new QWidget(MainWindowForm);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        _qvtkWidget = new QVTKWidget(centralWidget);
        _qvtkWidget->setObjectName(QStringLiteral("_qvtkWidget"));
        _qvtkWidget->setGeometry(QRect(30, 30, 730, 730));
        _pointCloudTable = new QTableWidget(centralWidget);
        _pointCloudTable->setObjectName(QStringLiteral("_pointCloudTable"));
        _pointCloudTable->setGeometry(QRect(790, 30, 460, 200));
        _processingTabWidget = new QTabWidget(centralWidget);
        _processingTabWidget->setObjectName(QStringLiteral("_processingTabWidget"));
        _processingTabWidget->setGeometry(QRect(790, 270, 460, 510));
        QFont font;
        font.setPointSize(20);
        _processingTabWidget->setFont(font);
        _processingTabWidget->setDocumentMode(false);
        _processingTabWidget->setTabsClosable(false);
        _processingTabWidget->setMovable(false);
        _processingTabWidget->setTabBarAutoHide(false);
        _filterTab = new QWidget();
        _filterTab->setObjectName(QStringLiteral("_filterTab"));
        _filterTabWidget = new QTabWidget(_filterTab);
        _filterTabWidget->setObjectName(QStringLiteral("_filterTabWidget"));
        _filterTabWidget->setGeometry(QRect(20, 20, 420, 390));
        _voxelGridTab = new QWidget();
        _voxelGridTab->setObjectName(QStringLiteral("_voxelGridTab"));
        _voxelGridXLabel = new QLabel(_voxelGridTab);
        _voxelGridXLabel->setObjectName(QStringLiteral("_voxelGridXLabel"));
        _voxelGridXLabel->setGeometry(QRect(10, 20, 50, 30));
        _voxelGridXLabel->setFont(font);
        _voxelGridYLabel = new QLabel(_voxelGridTab);
        _voxelGridYLabel->setObjectName(QStringLiteral("_voxelGridYLabel"));
        _voxelGridYLabel->setGeometry(QRect(10, 70, 50, 30));
        _voxelGridYLabel->setFont(font);
        _voxelGridYSpinBox = new QDoubleSpinBox(_voxelGridTab);
        _voxelGridYSpinBox->setObjectName(QStringLiteral("_voxelGridYSpinBox"));
        _voxelGridYSpinBox->setGeometry(QRect(80, 70, 90, 30));
        _voxelGridYSpinBox->setFont(font);
        _voxelGridYSpinBox->setDecimals(3);
        _voxelGridYSpinBox->setMinimum(0.01);
        _voxelGridYSpinBox->setMaximum(1);
        _voxelGridYSpinBox->setSingleStep(0.01);
        _voxelGridYSpinBox->setValue(0.01);
        _voxelGridZSpinBox = new QDoubleSpinBox(_voxelGridTab);
        _voxelGridZSpinBox->setObjectName(QStringLiteral("_voxelGridZSpinBox"));
        _voxelGridZSpinBox->setGeometry(QRect(80, 120, 90, 30));
        _voxelGridZSpinBox->setFont(font);
        _voxelGridZSpinBox->setDecimals(3);
        _voxelGridZSpinBox->setMinimum(0.01);
        _voxelGridZSpinBox->setMaximum(1);
        _voxelGridZSpinBox->setSingleStep(0.01);
        _voxelGridZSpinBox->setValue(0.01);
        _voxelGridXSpinBox = new QDoubleSpinBox(_voxelGridTab);
        _voxelGridXSpinBox->setObjectName(QStringLiteral("_voxelGridXSpinBox"));
        _voxelGridXSpinBox->setGeometry(QRect(80, 20, 90, 30));
        _voxelGridXSpinBox->setFont(font);
        _voxelGridXSpinBox->setDecimals(3);
        _voxelGridXSpinBox->setMinimum(0.01);
        _voxelGridXSpinBox->setMaximum(1);
        _voxelGridXSpinBox->setSingleStep(0.01);
        _voxelGridXSpinBox->setValue(0.01);
        _voxelGridZLabel = new QLabel(_voxelGridTab);
        _voxelGridZLabel->setObjectName(QStringLiteral("_voxelGridZLabel"));
        _voxelGridZLabel->setGeometry(QRect(10, 120, 50, 30));
        _voxelGridZLabel->setFont(font);
        _filterTabWidget->addTab(_voxelGridTab, QString());
        _boundingBoxTab = new QWidget();
        _boundingBoxTab->setObjectName(QStringLiteral("_boundingBoxTab"));
        _boundingBoxMinYSpinBox = new QDoubleSpinBox(_boundingBoxTab);
        _boundingBoxMinYSpinBox->setObjectName(QStringLiteral("_boundingBoxMinYSpinBox"));
        _boundingBoxMinYSpinBox->setGeometry(QRect(80, 70, 95, 30));
        _boundingBoxMinYSpinBox->setFont(font);
        _boundingBoxMinYSpinBox->setDecimals(3);
        _boundingBoxMinYSpinBox->setMinimum(-1);
        _boundingBoxMinYSpinBox->setMaximum(1);
        _boundingBoxMinYSpinBox->setSingleStep(0.1);
        _boundingBoxMinYSpinBox->setValue(-1);
        _boundingBoxZLabel = new QLabel(_boundingBoxTab);
        _boundingBoxZLabel->setObjectName(QStringLiteral("_boundingBoxZLabel"));
        _boundingBoxZLabel->setGeometry(QRect(10, 120, 50, 30));
        _boundingBoxZLabel->setFont(font);
        _boundingBoxMinXSpinBox = new QDoubleSpinBox(_boundingBoxTab);
        _boundingBoxMinXSpinBox->setObjectName(QStringLiteral("_boundingBoxMinXSpinBox"));
        _boundingBoxMinXSpinBox->setGeometry(QRect(80, 20, 95, 30));
        _boundingBoxMinXSpinBox->setFont(font);
        _boundingBoxMinXSpinBox->setDecimals(3);
        _boundingBoxMinXSpinBox->setMinimum(-1);
        _boundingBoxMinXSpinBox->setMaximum(1);
        _boundingBoxMinXSpinBox->setSingleStep(0.1);
        _boundingBoxMinXSpinBox->setValue(-1);
        _boundingBoxXLabel = new QLabel(_boundingBoxTab);
        _boundingBoxXLabel->setObjectName(QStringLiteral("_boundingBoxXLabel"));
        _boundingBoxXLabel->setGeometry(QRect(10, 20, 50, 30));
        _boundingBoxXLabel->setFont(font);
        _boundingBoxMinZSpinBox = new QDoubleSpinBox(_boundingBoxTab);
        _boundingBoxMinZSpinBox->setObjectName(QStringLiteral("_boundingBoxMinZSpinBox"));
        _boundingBoxMinZSpinBox->setGeometry(QRect(80, 120, 95, 30));
        _boundingBoxMinZSpinBox->setFont(font);
        _boundingBoxMinZSpinBox->setDecimals(3);
        _boundingBoxMinZSpinBox->setMinimum(-1);
        _boundingBoxMinZSpinBox->setMaximum(1);
        _boundingBoxMinZSpinBox->setSingleStep(0.1);
        _boundingBoxMinZSpinBox->setValue(-1);
        _boundingBoxYLabel = new QLabel(_boundingBoxTab);
        _boundingBoxYLabel->setObjectName(QStringLiteral("_boundingBoxYLabel"));
        _boundingBoxYLabel->setGeometry(QRect(10, 70, 50, 30));
        _boundingBoxYLabel->setFont(font);
        _boundingBoxMaxXSpinBox = new QDoubleSpinBox(_boundingBoxTab);
        _boundingBoxMaxXSpinBox->setObjectName(QStringLiteral("_boundingBoxMaxXSpinBox"));
        _boundingBoxMaxXSpinBox->setGeometry(QRect(230, 20, 95, 30));
        _boundingBoxMaxXSpinBox->setFont(font);
        _boundingBoxMaxXSpinBox->setDecimals(3);
        _boundingBoxMaxXSpinBox->setMinimum(-1);
        _boundingBoxMaxXSpinBox->setMaximum(1);
        _boundingBoxMaxXSpinBox->setSingleStep(0.1);
        _boundingBoxMaxXSpinBox->setValue(1);
        _boundingBoxMaxZSpinBox = new QDoubleSpinBox(_boundingBoxTab);
        _boundingBoxMaxZSpinBox->setObjectName(QStringLiteral("_boundingBoxMaxZSpinBox"));
        _boundingBoxMaxZSpinBox->setGeometry(QRect(230, 120, 95, 30));
        _boundingBoxMaxZSpinBox->setFont(font);
        _boundingBoxMaxZSpinBox->setDecimals(3);
        _boundingBoxMaxZSpinBox->setMinimum(-1);
        _boundingBoxMaxZSpinBox->setMaximum(1);
        _boundingBoxMaxZSpinBox->setSingleStep(0.1);
        _boundingBoxMaxZSpinBox->setValue(1);
        _boundingBoxMaxYSpinBox = new QDoubleSpinBox(_boundingBoxTab);
        _boundingBoxMaxYSpinBox->setObjectName(QStringLiteral("_boundingBoxMaxYSpinBox"));
        _boundingBoxMaxYSpinBox->setGeometry(QRect(230, 70, 95, 30));
        _boundingBoxMaxYSpinBox->setFont(font);
        _boundingBoxMaxYSpinBox->setDecimals(3);
        _boundingBoxMaxYSpinBox->setMinimum(-1);
        _boundingBoxMaxYSpinBox->setMaximum(1);
        _boundingBoxMaxYSpinBox->setSingleStep(0.1);
        _boundingBoxMaxYSpinBox->setValue(1);
        _boundingBoxXShiftLabel = new QLabel(_boundingBoxTab);
        _boundingBoxXShiftLabel->setObjectName(QStringLiteral("_boundingBoxXShiftLabel"));
        _boundingBoxXShiftLabel->setGeometry(QRect(200, 20, 50, 30));
        _boundingBoxXShiftLabel->setFont(font);
        _boundingBoxYShiftLabel = new QLabel(_boundingBoxTab);
        _boundingBoxYShiftLabel->setObjectName(QStringLiteral("_boundingBoxYShiftLabel"));
        _boundingBoxYShiftLabel->setGeometry(QRect(200, 70, 50, 30));
        _boundingBoxYShiftLabel->setFont(font);
        _boundingBoxZShiftLabel = new QLabel(_boundingBoxTab);
        _boundingBoxZShiftLabel->setObjectName(QStringLiteral("_boundingBoxZShiftLabel"));
        _boundingBoxZShiftLabel->setGeometry(QRect(200, 120, 50, 30));
        _boundingBoxZShiftLabel->setFont(font);
        _filterTabWidget->addTab(_boundingBoxTab, QString());
        _filterProcessingButton = new QPushButton(_filterTab);
        _filterProcessingButton->setObjectName(QStringLiteral("_filterProcessingButton"));
        _filterProcessingButton->setGeometry(QRect(20, 420, 150, 40));
        QFont font1;
        font1.setPointSize(16);
        _filterProcessingButton->setFont(font1);
        _processingTabWidget->addTab(_filterTab, QString());
        _keypointTab = new QWidget();
        _keypointTab->setObjectName(QStringLiteral("_keypointTab"));
        _keypointTabWidget = new QTabWidget(_keypointTab);
        _keypointTabWidget->setObjectName(QStringLiteral("_keypointTabWidget"));
        _keypointTabWidget->setGeometry(QRect(20, 20, 420, 390));
        _sift3DTab = new QWidget();
        _sift3DTab->setObjectName(QStringLiteral("_sift3DTab"));
        _siftMinScaleLabel = new QLabel(_sift3DTab);
        _siftMinScaleLabel->setObjectName(QStringLiteral("_siftMinScaleLabel"));
        _siftMinScaleLabel->setGeometry(QRect(10, 20, 130, 30));
        _siftNROctavesLabel = new QLabel(_sift3DTab);
        _siftNROctavesLabel->setObjectName(QStringLiteral("_siftNROctavesLabel"));
        _siftNROctavesLabel->setGeometry(QRect(10, 70, 160, 30));
        _siftNRScalesPerOctaveLabel = new QLabel(_sift3DTab);
        _siftNRScalesPerOctaveLabel->setObjectName(QStringLiteral("_siftNRScalesPerOctaveLabel"));
        _siftNRScalesPerOctaveLabel->setGeometry(QRect(10, 120, 250, 30));
        _siftMinScaleSpinBox = new QDoubleSpinBox(_sift3DTab);
        _siftMinScaleSpinBox->setObjectName(QStringLiteral("_siftMinScaleSpinBox"));
        _siftMinScaleSpinBox->setGeometry(QRect(260, 20, 90, 30));
        _siftMinScaleSpinBox->setDecimals(3);
        _siftMinScaleSpinBox->setMinimum(0.01);
        _siftMinScaleSpinBox->setMaximum(1);
        _siftMinScaleSpinBox->setSingleStep(0.01);
        _siftMinScaleSpinBox->setValue(0.01);
        _siftMinContrastLabel = new QLabel(_sift3DTab);
        _siftMinContrastLabel->setObjectName(QStringLiteral("_siftMinContrastLabel"));
        _siftMinContrastLabel->setGeometry(QRect(10, 170, 160, 30));
        _siftMinContrastSpinBox = new QDoubleSpinBox(_sift3DTab);
        _siftMinContrastSpinBox->setObjectName(QStringLiteral("_siftMinContrastSpinBox"));
        _siftMinContrastSpinBox->setGeometry(QRect(260, 170, 90, 30));
        _siftMinContrastSpinBox->setDecimals(3);
        _siftMinContrastSpinBox->setSingleStep(0.1);
        _siftNROctavesSpinBox = new QSpinBox(_sift3DTab);
        _siftNROctavesSpinBox->setObjectName(QStringLiteral("_siftNROctavesSpinBox"));
        _siftNROctavesSpinBox->setGeometry(QRect(260, 70, 90, 30));
        _siftNROctavesSpinBox->setMinimum(1);
        _siftNROctavesSpinBox->setValue(3);
        _siftNRScalesPerOctaveSpinBox = new QSpinBox(_sift3DTab);
        _siftNRScalesPerOctaveSpinBox->setObjectName(QStringLiteral("_siftNRScalesPerOctaveSpinBox"));
        _siftNRScalesPerOctaveSpinBox->setGeometry(QRect(260, 120, 90, 30));
        _siftNRScalesPerOctaveSpinBox->setMinimum(1);
        _siftNRScalesPerOctaveSpinBox->setValue(2);
        _keypointTabWidget->addTab(_sift3DTab, QString());
        _harris3DTab = new QWidget();
        _harris3DTab->setObjectName(QStringLiteral("_harris3DTab"));
        _harrisSetRadiusSearchLabel = new QLabel(_harris3DTab);
        _harrisSetRadiusSearchLabel->setObjectName(QStringLiteral("_harrisSetRadiusSearchLabel"));
        _harrisSetRadiusSearchLabel->setGeometry(QRect(10, 120, 200, 30));
        _harrisRadiusLabel = new QLabel(_harris3DTab);
        _harrisRadiusLabel->setObjectName(QStringLiteral("_harrisRadiusLabel"));
        _harrisRadiusLabel->setGeometry(QRect(10, 70, 130, 30));
        _harrisRadiusSpinBox = new QDoubleSpinBox(_harris3DTab);
        _harrisRadiusSpinBox->setObjectName(QStringLiteral("_harrisRadiusSpinBox"));
        _harrisRadiusSpinBox->setGeometry(QRect(260, 70, 90, 30));
        _harrisRadiusSpinBox->setDecimals(3);
        _harrisRadiusSpinBox->setMinimum(0.01);
        _harrisRadiusSpinBox->setMaximum(1);
        _harrisRadiusSpinBox->setSingleStep(0.01);
        _harrisRadiusSpinBox->setValue(0.01);
        _harrisRadiusSearchSpinBox = new QDoubleSpinBox(_harris3DTab);
        _harrisRadiusSearchSpinBox->setObjectName(QStringLiteral("_harrisRadiusSearchSpinBox"));
        _harrisRadiusSearchSpinBox->setGeometry(QRect(260, 120, 90, 30));
        _harrisRadiusSearchSpinBox->setDecimals(3);
        _harrisRadiusSearchSpinBox->setMinimum(0.01);
        _harrisRadiusSearchSpinBox->setMaximum(1);
        _harrisRadiusSearchSpinBox->setSingleStep(0.01);
        _harrisRadiusSearchSpinBox->setValue(0.01);
        _harrisMethodLabel = new QLabel(_harris3DTab);
        _harrisMethodLabel->setObjectName(QStringLiteral("_harrisMethodLabel"));
        _harrisMethodLabel->setGeometry(QRect(10, 20, 130, 30));
        _harrisMethodComboBox = new QComboBox(_harris3DTab);
        _harrisMethodComboBox->setObjectName(QStringLiteral("_harrisMethodComboBox"));
        _harrisMethodComboBox->setGeometry(QRect(230, 20, 120, 30));
        _keypointTabWidget->addTab(_harris3DTab, QString());
        _keypointProcessingButton = new QPushButton(_keypointTab);
        _keypointProcessingButton->setObjectName(QStringLiteral("_keypointProcessingButton"));
        _keypointProcessingButton->setGeometry(QRect(20, 420, 150, 40));
        _keypointProcessingButton->setFont(font1);
        _processingTabWidget->addTab(_keypointTab, QString());
        _correspondencesTab = new QWidget();
        _correspondencesTab->setObjectName(QStringLiteral("_correspondencesTab"));
        _correspondencesTabWidget = new QTabWidget(_correspondencesTab);
        _correspondencesTabWidget->setObjectName(QStringLiteral("_correspondencesTabWidget"));
        _correspondencesTabWidget->setGeometry(QRect(20, 20, 420, 390));
        _fpfhTab = new QWidget();
        _fpfhTab->setObjectName(QStringLiteral("_fpfhTab"));
        _fpfhNormalRadiusLabel = new QLabel(_fpfhTab);
        _fpfhNormalRadiusLabel->setObjectName(QStringLiteral("_fpfhNormalRadiusLabel"));
        _fpfhNormalRadiusLabel->setGeometry(QRect(10, 70, 180, 30));
        _fpfhdescriptorRadiusLabel = new QLabel(_fpfhTab);
        _fpfhdescriptorRadiusLabel->setObjectName(QStringLiteral("_fpfhdescriptorRadiusLabel"));
        _fpfhdescriptorRadiusLabel->setGeometry(QRect(10, 20, 220, 30));
        _fpfhDescriptorRadiusSpinBox = new QDoubleSpinBox(_fpfhTab);
        _fpfhDescriptorRadiusSpinBox->setObjectName(QStringLiteral("_fpfhDescriptorRadiusSpinBox"));
        _fpfhDescriptorRadiusSpinBox->setGeometry(QRect(300, 20, 90, 30));
        _fpfhDescriptorRadiusSpinBox->setDecimals(3);
        _fpfhDescriptorRadiusSpinBox->setMinimum(0.01);
        _fpfhDescriptorRadiusSpinBox->setMaximum(1);
        _fpfhDescriptorRadiusSpinBox->setSingleStep(0.01);
        _fpfhDescriptorRadiusSpinBox->setValue(0.05);
        _fpfhCorrespondencesKSpinBox = new QSpinBox(_fpfhTab);
        _fpfhCorrespondencesKSpinBox->setObjectName(QStringLiteral("_fpfhCorrespondencesKSpinBox"));
        _fpfhCorrespondencesKSpinBox->setGeometry(QRect(300, 120, 90, 30));
        _fpfhCorrespondencesKSpinBox->setMinimum(1);
        _fpfhCorrespondencesKSpinBox->setMaximum(10);
        _fpfhCorrespondencesKSpinBox->setValue(1);
        _fpfhCorrespondencesKLabel = new QLabel(_fpfhTab);
        _fpfhCorrespondencesKLabel->setObjectName(QStringLiteral("_fpfhCorrespondencesKLabel"));
        _fpfhCorrespondencesKLabel->setGeometry(QRect(10, 120, 220, 30));
        _fpfhNormalRadiusSpinBox = new QDoubleSpinBox(_fpfhTab);
        _fpfhNormalRadiusSpinBox->setObjectName(QStringLiteral("_fpfhNormalRadiusSpinBox"));
        _fpfhNormalRadiusSpinBox->setGeometry(QRect(300, 70, 90, 30));
        _fpfhNormalRadiusSpinBox->setDecimals(3);
        _fpfhNormalRadiusSpinBox->setMinimum(0.01);
        _fpfhNormalRadiusSpinBox->setMaximum(1);
        _fpfhNormalRadiusSpinBox->setSingleStep(0.01);
        _fpfhNormalRadiusSpinBox->setValue(0.01);
        _fpfhRejectorInlierThresholdLabel = new QLabel(_fpfhTab);
        _fpfhRejectorInlierThresholdLabel->setObjectName(QStringLiteral("_fpfhRejectorInlierThresholdLabel"));
        _fpfhRejectorInlierThresholdLabel->setGeometry(QRect(10, 170, 280, 30));
        _fpfhRejectorInlierThresholdSpinBox = new QDoubleSpinBox(_fpfhTab);
        _fpfhRejectorInlierThresholdSpinBox->setObjectName(QStringLiteral("_fpfhRejectorInlierThresholdSpinBox"));
        _fpfhRejectorInlierThresholdSpinBox->setGeometry(QRect(300, 170, 90, 30));
        _fpfhRejectorInlierThresholdSpinBox->setDecimals(3);
        _fpfhRejectorInlierThresholdSpinBox->setMinimum(0.1);
        _fpfhRejectorInlierThresholdSpinBox->setSingleStep(0.1);
        _fpfhRejectorInlierThresholdSpinBox->setValue(1);
        _correspondencesTabWidget->addTab(_fpfhTab, QString());
        _shotRGBTab = new QWidget();
        _shotRGBTab->setObjectName(QStringLiteral("_shotRGBTab"));
        _shotdescriptorRadiusLabel = new QLabel(_shotRGBTab);
        _shotdescriptorRadiusLabel->setObjectName(QStringLiteral("_shotdescriptorRadiusLabel"));
        _shotdescriptorRadiusLabel->setGeometry(QRect(10, 20, 220, 30));
        _shotCorrespondencesKSpinBox = new QSpinBox(_shotRGBTab);
        _shotCorrespondencesKSpinBox->setObjectName(QStringLiteral("_shotCorrespondencesKSpinBox"));
        _shotCorrespondencesKSpinBox->setGeometry(QRect(300, 120, 90, 30));
        _shotCorrespondencesKSpinBox->setMinimum(1);
        _shotCorrespondencesKSpinBox->setMaximum(10);
        _shotCorrespondencesKSpinBox->setValue(1);
        _shotNormalRadiusLabel = new QLabel(_shotRGBTab);
        _shotNormalRadiusLabel->setObjectName(QStringLiteral("_shotNormalRadiusLabel"));
        _shotNormalRadiusLabel->setGeometry(QRect(10, 70, 180, 30));
        _shotNormalRadiusSpinBox = new QDoubleSpinBox(_shotRGBTab);
        _shotNormalRadiusSpinBox->setObjectName(QStringLiteral("_shotNormalRadiusSpinBox"));
        _shotNormalRadiusSpinBox->setGeometry(QRect(300, 70, 90, 30));
        _shotNormalRadiusSpinBox->setDecimals(3);
        _shotNormalRadiusSpinBox->setMinimum(0.01);
        _shotNormalRadiusSpinBox->setMaximum(1);
        _shotNormalRadiusSpinBox->setSingleStep(0.01);
        _shotNormalRadiusSpinBox->setValue(0.01);
        _shotCorrespondencesKLabel = new QLabel(_shotRGBTab);
        _shotCorrespondencesKLabel->setObjectName(QStringLiteral("_shotCorrespondencesKLabel"));
        _shotCorrespondencesKLabel->setGeometry(QRect(10, 120, 220, 30));
        _shotDescriptorRadiusSpinBox = new QDoubleSpinBox(_shotRGBTab);
        _shotDescriptorRadiusSpinBox->setObjectName(QStringLiteral("_shotDescriptorRadiusSpinBox"));
        _shotDescriptorRadiusSpinBox->setGeometry(QRect(300, 20, 90, 30));
        _shotDescriptorRadiusSpinBox->setDecimals(3);
        _shotDescriptorRadiusSpinBox->setMinimum(0.01);
        _shotDescriptorRadiusSpinBox->setMaximum(1);
        _shotDescriptorRadiusSpinBox->setSingleStep(0.01);
        _shotDescriptorRadiusSpinBox->setValue(0.04);
        _shotRejectorInlierThresholdSpinBox = new QDoubleSpinBox(_shotRGBTab);
        _shotRejectorInlierThresholdSpinBox->setObjectName(QStringLiteral("_shotRejectorInlierThresholdSpinBox"));
        _shotRejectorInlierThresholdSpinBox->setGeometry(QRect(300, 170, 90, 30));
        _shotRejectorInlierThresholdSpinBox->setDecimals(3);
        _shotRejectorInlierThresholdSpinBox->setMinimum(0.1);
        _shotRejectorInlierThresholdSpinBox->setSingleStep(0.1);
        _shotRejectorInlierThresholdSpinBox->setValue(1);
        _shotRejectorInlierThresholdLabel = new QLabel(_shotRGBTab);
        _shotRejectorInlierThresholdLabel->setObjectName(QStringLiteral("_shotRejectorInlierThresholdLabel"));
        _shotRejectorInlierThresholdLabel->setGeometry(QRect(10, 170, 280, 30));
        _correspondencesTabWidget->addTab(_shotRGBTab, QString());
        _pfhTab = new QWidget();
        _pfhTab->setObjectName(QStringLiteral("_pfhTab"));
        _pfhdescriptorKSearchLabel = new QLabel(_pfhTab);
        _pfhdescriptorKSearchLabel->setObjectName(QStringLiteral("_pfhdescriptorKSearchLabel"));
        _pfhdescriptorKSearchLabel->setGeometry(QRect(10, 20, 220, 30));
        _pfhCorrespondencesKSpinBox = new QSpinBox(_pfhTab);
        _pfhCorrespondencesKSpinBox->setObjectName(QStringLiteral("_pfhCorrespondencesKSpinBox"));
        _pfhCorrespondencesKSpinBox->setGeometry(QRect(300, 120, 90, 30));
        _pfhCorrespondencesKSpinBox->setMinimum(1);
        _pfhCorrespondencesKSpinBox->setMaximum(10);
        _pfhCorrespondencesKSpinBox->setValue(1);
        _pfhNormalRadiusLabel = new QLabel(_pfhTab);
        _pfhNormalRadiusLabel->setObjectName(QStringLiteral("_pfhNormalRadiusLabel"));
        _pfhNormalRadiusLabel->setGeometry(QRect(10, 70, 180, 30));
        _pfhCorrespondencesKLabel = new QLabel(_pfhTab);
        _pfhCorrespondencesKLabel->setObjectName(QStringLiteral("_pfhCorrespondencesKLabel"));
        _pfhCorrespondencesKLabel->setGeometry(QRect(10, 120, 220, 30));
        _pfhNormalRadiusSpinBox = new QDoubleSpinBox(_pfhTab);
        _pfhNormalRadiusSpinBox->setObjectName(QStringLiteral("_pfhNormalRadiusSpinBox"));
        _pfhNormalRadiusSpinBox->setGeometry(QRect(300, 70, 90, 30));
        _pfhNormalRadiusSpinBox->setDecimals(3);
        _pfhNormalRadiusSpinBox->setMinimum(0.01);
        _pfhNormalRadiusSpinBox->setMaximum(1);
        _pfhNormalRadiusSpinBox->setSingleStep(0.01);
        _pfhNormalRadiusSpinBox->setValue(0.01);
        _pfhDescriptorKSearchSpinBox = new QSpinBox(_pfhTab);
        _pfhDescriptorKSearchSpinBox->setObjectName(QStringLiteral("_pfhDescriptorKSearchSpinBox"));
        _pfhDescriptorKSearchSpinBox->setGeometry(QRect(300, 20, 90, 30));
        _pfhDescriptorKSearchSpinBox->setMinimum(1);
        _pfhDescriptorKSearchSpinBox->setValue(50);
        _pfhRejectorInlierThresholdSpinBox = new QDoubleSpinBox(_pfhTab);
        _pfhRejectorInlierThresholdSpinBox->setObjectName(QStringLiteral("_pfhRejectorInlierThresholdSpinBox"));
        _pfhRejectorInlierThresholdSpinBox->setGeometry(QRect(300, 170, 90, 30));
        _pfhRejectorInlierThresholdSpinBox->setDecimals(3);
        _pfhRejectorInlierThresholdSpinBox->setMinimum(0.1);
        _pfhRejectorInlierThresholdSpinBox->setSingleStep(0.1);
        _pfhRejectorInlierThresholdSpinBox->setValue(1);
        _pfhRejectorInlierThresholdLabel = new QLabel(_pfhTab);
        _pfhRejectorInlierThresholdLabel->setObjectName(QStringLiteral("_pfhRejectorInlierThresholdLabel"));
        _pfhRejectorInlierThresholdLabel->setGeometry(QRect(10, 170, 280, 30));
        _correspondencesTabWidget->addTab(_pfhTab, QString());
        _pfhrgbTab = new QWidget();
        _pfhrgbTab->setObjectName(QStringLiteral("_pfhrgbTab"));
        _pfhrgbRejectorInlierThresholdLabel = new QLabel(_pfhrgbTab);
        _pfhrgbRejectorInlierThresholdLabel->setObjectName(QStringLiteral("_pfhrgbRejectorInlierThresholdLabel"));
        _pfhrgbRejectorInlierThresholdLabel->setGeometry(QRect(10, 170, 280, 30));
        _pfhrgbRejectorInlierThresholdSpinBox = new QDoubleSpinBox(_pfhrgbTab);
        _pfhrgbRejectorInlierThresholdSpinBox->setObjectName(QStringLiteral("_pfhrgbRejectorInlierThresholdSpinBox"));
        _pfhrgbRejectorInlierThresholdSpinBox->setGeometry(QRect(300, 170, 90, 30));
        _pfhrgbRejectorInlierThresholdSpinBox->setDecimals(3);
        _pfhrgbRejectorInlierThresholdSpinBox->setMinimum(0.1);
        _pfhrgbRejectorInlierThresholdSpinBox->setSingleStep(0.1);
        _pfhrgbRejectorInlierThresholdSpinBox->setValue(1);
        _pfhrgbDescriptorKSearchSpinBox = new QSpinBox(_pfhrgbTab);
        _pfhrgbDescriptorKSearchSpinBox->setObjectName(QStringLiteral("_pfhrgbDescriptorKSearchSpinBox"));
        _pfhrgbDescriptorKSearchSpinBox->setGeometry(QRect(300, 20, 90, 30));
        _pfhrgbDescriptorKSearchSpinBox->setMinimum(1);
        _pfhrgbDescriptorKSearchSpinBox->setValue(50);
        _pfhrgbCorrespondencesKLabel = new QLabel(_pfhrgbTab);
        _pfhrgbCorrespondencesKLabel->setObjectName(QStringLiteral("_pfhrgbCorrespondencesKLabel"));
        _pfhrgbCorrespondencesKLabel->setGeometry(QRect(10, 120, 220, 30));
        _pfhrgbNormalRadiusSpinBox = new QDoubleSpinBox(_pfhrgbTab);
        _pfhrgbNormalRadiusSpinBox->setObjectName(QStringLiteral("_pfhrgbNormalRadiusSpinBox"));
        _pfhrgbNormalRadiusSpinBox->setGeometry(QRect(300, 70, 90, 30));
        _pfhrgbNormalRadiusSpinBox->setDecimals(3);
        _pfhrgbNormalRadiusSpinBox->setMinimum(0.01);
        _pfhrgbNormalRadiusSpinBox->setMaximum(1);
        _pfhrgbNormalRadiusSpinBox->setSingleStep(0.01);
        _pfhrgbNormalRadiusSpinBox->setValue(0.01);
        _pfhrgbdescriptorKSearchLabel = new QLabel(_pfhrgbTab);
        _pfhrgbdescriptorKSearchLabel->setObjectName(QStringLiteral("_pfhrgbdescriptorKSearchLabel"));
        _pfhrgbdescriptorKSearchLabel->setGeometry(QRect(10, 20, 220, 30));
        _pfhrgbNormalRadiusLabel = new QLabel(_pfhrgbTab);
        _pfhrgbNormalRadiusLabel->setObjectName(QStringLiteral("_pfhrgbNormalRadiusLabel"));
        _pfhrgbNormalRadiusLabel->setGeometry(QRect(10, 70, 180, 30));
        _pfhrgbCorrespondencesKSpinBox = new QSpinBox(_pfhrgbTab);
        _pfhrgbCorrespondencesKSpinBox->setObjectName(QStringLiteral("_pfhrgbCorrespondencesKSpinBox"));
        _pfhrgbCorrespondencesKSpinBox->setGeometry(QRect(300, 120, 90, 30));
        _pfhrgbCorrespondencesKSpinBox->setMinimum(1);
        _pfhrgbCorrespondencesKSpinBox->setMaximum(10);
        _pfhrgbCorrespondencesKSpinBox->setValue(1);
        _correspondencesTabWidget->addTab(_pfhrgbTab, QString());
        _correspondencesProcessingButton = new QPushButton(_correspondencesTab);
        _correspondencesProcessingButton->setObjectName(QStringLiteral("_correspondencesProcessingButton"));
        _correspondencesProcessingButton->setGeometry(QRect(20, 420, 150, 40));
        _correspondencesProcessingButton->setFont(font1);
        _processingTabWidget->addTab(_correspondencesTab, QString());
        _regestrationTab = new QWidget();
        _regestrationTab->setObjectName(QStringLiteral("_regestrationTab"));
        _regestrationProcessingButton = new QPushButton(_regestrationTab);
        _regestrationProcessingButton->setObjectName(QStringLiteral("_regestrationProcessingButton"));
        _regestrationProcessingButton->setGeometry(QRect(20, 420, 150, 40));
        _regestrationProcessingButton->setFont(font1);
        _regestrationTabWidget = new QTabWidget(_regestrationTab);
        _regestrationTabWidget->setObjectName(QStringLiteral("_regestrationTabWidget"));
        _regestrationTabWidget->setGeometry(QRect(20, 20, 420, 390));
        _icpTab = new QWidget();
        _icpTab->setObjectName(QStringLiteral("_icpTab"));
        _icpOutlierThresholdLabel = new QLabel(_icpTab);
        _icpOutlierThresholdLabel->setObjectName(QStringLiteral("_icpOutlierThresholdLabel"));
        _icpOutlierThresholdLabel->setGeometry(QRect(10, 70, 280, 30));
        _icpCorrespondenceDistanceLabel = new QLabel(_icpTab);
        _icpCorrespondenceDistanceLabel->setObjectName(QStringLiteral("_icpCorrespondenceDistanceLabel"));
        _icpCorrespondenceDistanceLabel->setGeometry(QRect(10, 20, 280, 30));
        _icpCorrespondenceDistanceSpinBox = new QDoubleSpinBox(_icpTab);
        _icpCorrespondenceDistanceSpinBox->setObjectName(QStringLiteral("_icpCorrespondenceDistanceSpinBox"));
        _icpCorrespondenceDistanceSpinBox->setGeometry(QRect(320, 20, 80, 30));
        _icpCorrespondenceDistanceSpinBox->setMinimum(0.01);
        _icpCorrespondenceDistanceSpinBox->setMaximum(1);
        _icpCorrespondenceDistanceSpinBox->setSingleStep(0.01);
        _icpCorrespondenceDistanceSpinBox->setValue(0.05);
        _icpTransformationEpsilonLabel = new QLabel(_icpTab);
        _icpTransformationEpsilonLabel->setObjectName(QStringLiteral("_icpTransformationEpsilonLabel"));
        _icpTransformationEpsilonLabel->setGeometry(QRect(10, 120, 280, 30));
        _icpOutlierThresholdSpinBox = new QDoubleSpinBox(_icpTab);
        _icpOutlierThresholdSpinBox->setObjectName(QStringLiteral("_icpOutlierThresholdSpinBox"));
        _icpOutlierThresholdSpinBox->setGeometry(QRect(320, 70, 80, 30));
        _icpOutlierThresholdSpinBox->setMinimum(0.01);
        _icpOutlierThresholdSpinBox->setMaximum(1);
        _icpOutlierThresholdSpinBox->setSingleStep(0.01);
        _icpOutlierThresholdSpinBox->setValue(0.05);
        _icpMaxIterationsLabel = new QLabel(_icpTab);
        _icpMaxIterationsLabel->setObjectName(QStringLiteral("_icpMaxIterationsLabel"));
        _icpMaxIterationsLabel->setGeometry(QRect(10, 170, 280, 30));
        _icpMaxIterationsSpinBox = new QSpinBox(_icpTab);
        _icpMaxIterationsSpinBox->setObjectName(QStringLiteral("_icpMaxIterationsSpinBox"));
        _icpMaxIterationsSpinBox->setGeometry(QRect(320, 170, 80, 30));
        _icpMaxIterationsSpinBox->setMinimum(1);
        _icpMaxIterationsSpinBox->setMaximum(10000);
        _icpMaxIterationsSpinBox->setValue(1000);
        _icpTransformationEpsilonSpinBox = new QDoubleSpinBox(_icpTab);
        _icpTransformationEpsilonSpinBox->setObjectName(QStringLiteral("_icpTransformationEpsilonSpinBox"));
        _icpTransformationEpsilonSpinBox->setGeometry(QRect(275, 120, 125, 30));
        _icpTransformationEpsilonSpinBox->setDecimals(6);
        _icpTransformationEpsilonSpinBox->setMinimum(1e-6);
        _icpTransformationEpsilonSpinBox->setMaximum(1);
        _icpTransformationEpsilonSpinBox->setSingleStep(1e-6);
        _icpTransformationEpsilonSpinBox->setValue(1e-6);
        _regestrationTabWidget->addTab(_icpTab, QString());
        _processingTabWidget->addTab(_regestrationTab, QString());
        _reconstructTab = new QWidget();
        _reconstructTab->setObjectName(QStringLiteral("_reconstructTab"));
        _reconstructTabWidget = new QTabWidget(_reconstructTab);
        _reconstructTabWidget->setObjectName(QStringLiteral("_reconstructTabWidget"));
        _reconstructTabWidget->setGeometry(QRect(20, 20, 420, 390));
        _greedyProjectionTab = new QWidget();
        _greedyProjectionTab->setObjectName(QStringLiteral("_greedyProjectionTab"));
        _greedyProjectionMuLabel = new QLabel(_greedyProjectionTab);
        _greedyProjectionMuLabel->setObjectName(QStringLiteral("_greedyProjectionMuLabel"));
        _greedyProjectionMuLabel->setGeometry(QRect(10, 70, 200, 30));
        _greedyProjectionSearchRadiusLabel = new QLabel(_greedyProjectionTab);
        _greedyProjectionSearchRadiusLabel->setObjectName(QStringLiteral("_greedyProjectionSearchRadiusLabel"));
        _greedyProjectionSearchRadiusLabel->setGeometry(QRect(10, 20, 200, 30));
        _greedyProjectionSearchRadiusSpinBox = new QDoubleSpinBox(_greedyProjectionTab);
        _greedyProjectionSearchRadiusSpinBox->setObjectName(QStringLiteral("_greedyProjectionSearchRadiusSpinBox"));
        _greedyProjectionSearchRadiusSpinBox->setGeometry(QRect(300, 20, 100, 30));
        _greedyProjectionSearchRadiusSpinBox->setDecimals(3);
        _greedyProjectionSearchRadiusSpinBox->setMinimum(0.001);
        _greedyProjectionSearchRadiusSpinBox->setMaximum(1);
        _greedyProjectionSearchRadiusSpinBox->setSingleStep(0.001);
        _greedyProjectionSearchRadiusSpinBox->setValue(0.025);
        _greedyProjectionMaxNearestNeighborsLabel = new QLabel(_greedyProjectionTab);
        _greedyProjectionMaxNearestNeighborsLabel->setObjectName(QStringLiteral("_greedyProjectionMaxNearestNeighborsLabel"));
        _greedyProjectionMaxNearestNeighborsLabel->setGeometry(QRect(10, 120, 280, 30));
        _greedyProjectionMuSpinBox = new QDoubleSpinBox(_greedyProjectionTab);
        _greedyProjectionMuSpinBox->setObjectName(QStringLiteral("_greedyProjectionMuSpinBox"));
        _greedyProjectionMuSpinBox->setGeometry(QRect(300, 70, 100, 30));
        _greedyProjectionMuSpinBox->setDecimals(2);
        _greedyProjectionMuSpinBox->setMinimum(0.01);
        _greedyProjectionMuSpinBox->setMaximum(100);
        _greedyProjectionMuSpinBox->setSingleStep(0.1);
        _greedyProjectionMuSpinBox->setValue(2.5);
        _greedyProjectionMaxSurfaceAngleLabel = new QLabel(_greedyProjectionTab);
        _greedyProjectionMaxSurfaceAngleLabel->setObjectName(QStringLiteral("_greedyProjectionMaxSurfaceAngleLabel"));
        _greedyProjectionMaxSurfaceAngleLabel->setGeometry(QRect(10, 170, 280, 30));
        _greedyProjectionMaxNearestNeighborsSpinBox = new QSpinBox(_greedyProjectionTab);
        _greedyProjectionMaxNearestNeighborsSpinBox->setObjectName(QStringLiteral("_greedyProjectionMaxNearestNeighborsSpinBox"));
        _greedyProjectionMaxNearestNeighborsSpinBox->setGeometry(QRect(300, 120, 100, 30));
        _greedyProjectionMaxNearestNeighborsSpinBox->setMinimum(1);
        _greedyProjectionMaxNearestNeighborsSpinBox->setMaximum(1000);
        _greedyProjectionMaxNearestNeighborsSpinBox->setValue(100);
        _greedyProjectionMinAngleLabel = new QLabel(_greedyProjectionTab);
        _greedyProjectionMinAngleLabel->setObjectName(QStringLiteral("_greedyProjectionMinAngleLabel"));
        _greedyProjectionMinAngleLabel->setGeometry(QRect(10, 220, 280, 30));
        _greedyProjectionMaxAngleLabel = new QLabel(_greedyProjectionTab);
        _greedyProjectionMaxAngleLabel->setObjectName(QStringLiteral("_greedyProjectionMaxAngleLabel"));
        _greedyProjectionMaxAngleLabel->setGeometry(QRect(10, 270, 280, 30));
        _greedyProjectionMaxSurfaceAngleSpinBox = new QSpinBox(_greedyProjectionTab);
        _greedyProjectionMaxSurfaceAngleSpinBox->setObjectName(QStringLiteral("_greedyProjectionMaxSurfaceAngleSpinBox"));
        _greedyProjectionMaxSurfaceAngleSpinBox->setGeometry(QRect(300, 170, 100, 30));
        _greedyProjectionMaxSurfaceAngleSpinBox->setMaximum(360);
        _greedyProjectionMaxSurfaceAngleSpinBox->setValue(45);
        _greedyProjectionMinAngleSpinBox = new QSpinBox(_greedyProjectionTab);
        _greedyProjectionMinAngleSpinBox->setObjectName(QStringLiteral("_greedyProjectionMinAngleSpinBox"));
        _greedyProjectionMinAngleSpinBox->setGeometry(QRect(300, 220, 100, 30));
        _greedyProjectionMinAngleSpinBox->setMaximum(360);
        _greedyProjectionMinAngleSpinBox->setValue(10);
        _greedyProjectionMaxAngleSpinBox = new QSpinBox(_greedyProjectionTab);
        _greedyProjectionMaxAngleSpinBox->setObjectName(QStringLiteral("_greedyProjectionMaxAngleSpinBox"));
        _greedyProjectionMaxAngleSpinBox->setGeometry(QRect(300, 270, 100, 30));
        _greedyProjectionMaxAngleSpinBox->setMaximum(360);
        _greedyProjectionMaxAngleSpinBox->setValue(120);
        _greedyProjectNormalSearchRadiusSpinBox = new QDoubleSpinBox(_greedyProjectionTab);
        _greedyProjectNormalSearchRadiusSpinBox->setObjectName(QStringLiteral("_greedyProjectNormalSearchRadiusSpinBox"));
        _greedyProjectNormalSearchRadiusSpinBox->setGeometry(QRect(300, 310, 100, 30));
        _greedyProjectNormalSearchRadiusSpinBox->setDecimals(3);
        _greedyProjectNormalSearchRadiusSpinBox->setMinimum(0.01);
        _greedyProjectNormalSearchRadiusSpinBox->setMaximum(1);
        _greedyProjectNormalSearchRadiusSpinBox->setSingleStep(0.01);
        _greedyProjectNormalSearchRadiusSpinBox->setValue(0.01);
        _GreedyProjectNormalSearchRadiusLabel = new QLabel(_greedyProjectionTab);
        _GreedyProjectNormalSearchRadiusLabel->setObjectName(QStringLiteral("_GreedyProjectNormalSearchRadiusLabel"));
        _GreedyProjectNormalSearchRadiusLabel->setGeometry(QRect(10, 310, 250, 30));
        _reconstructTabWidget->addTab(_greedyProjectionTab, QString());
        _marchingCubesTab = new QWidget();
        _marchingCubesTab->setObjectName(QStringLiteral("_marchingCubesTab"));
        _marchingCubesGridResolutionXLabel = new QLabel(_marchingCubesTab);
        _marchingCubesGridResolutionXLabel->setObjectName(QStringLiteral("_marchingCubesGridResolutionXLabel"));
        _marchingCubesGridResolutionXLabel->setGeometry(QRect(10, 20, 280, 30));
        _marchingCubesGridResolutionZLabel = new QLabel(_marchingCubesTab);
        _marchingCubesGridResolutionZLabel->setObjectName(QStringLiteral("_marchingCubesGridResolutionZLabel"));
        _marchingCubesGridResolutionZLabel->setGeometry(QRect(10, 120, 280, 30));
        _marchingCubesGridResolutionYLabel = new QLabel(_marchingCubesTab);
        _marchingCubesGridResolutionYLabel->setObjectName(QStringLiteral("_marchingCubesGridResolutionYLabel"));
        _marchingCubesGridResolutionYLabel->setGeometry(QRect(10, 70, 280, 30));
        _marchingCubesGridResolutionYSpinBox = new QSpinBox(_marchingCubesTab);
        _marchingCubesGridResolutionYSpinBox->setObjectName(QStringLiteral("_marchingCubesGridResolutionYSpinBox"));
        _marchingCubesGridResolutionYSpinBox->setGeometry(QRect(300, 70, 100, 30));
        _marchingCubesGridResolutionYSpinBox->setMinimum(1);
        _marchingCubesGridResolutionYSpinBox->setMaximum(100);
        _marchingCubesGridResolutionYSpinBox->setValue(50);
        _marchingCubesGridResolutionXSpinBox = new QSpinBox(_marchingCubesTab);
        _marchingCubesGridResolutionXSpinBox->setObjectName(QStringLiteral("_marchingCubesGridResolutionXSpinBox"));
        _marchingCubesGridResolutionXSpinBox->setGeometry(QRect(300, 20, 100, 30));
        _marchingCubesGridResolutionXSpinBox->setMinimum(1);
        _marchingCubesGridResolutionXSpinBox->setMaximum(100);
        _marchingCubesGridResolutionXSpinBox->setValue(50);
        _marchingCubesGridResolutionZSpinBox = new QSpinBox(_marchingCubesTab);
        _marchingCubesGridResolutionZSpinBox->setObjectName(QStringLiteral("_marchingCubesGridResolutionZSpinBox"));
        _marchingCubesGridResolutionZSpinBox->setGeometry(QRect(300, 120, 100, 30));
        _marchingCubesGridResolutionZSpinBox->setMinimum(1);
        _marchingCubesGridResolutionZSpinBox->setMaximum(100);
        _marchingCubesGridResolutionZSpinBox->setValue(50);
        _marchingCubesIsoLevelLabel = new QLabel(_marchingCubesTab);
        _marchingCubesIsoLevelLabel->setObjectName(QStringLiteral("_marchingCubesIsoLevelLabel"));
        _marchingCubesIsoLevelLabel->setGeometry(QRect(10, 170, 200, 30));
        _marchingCubesIsoLevelSpinBox = new QDoubleSpinBox(_marchingCubesTab);
        _marchingCubesIsoLevelSpinBox->setObjectName(QStringLiteral("_marchingCubesIsoLevelSpinBox"));
        _marchingCubesIsoLevelSpinBox->setGeometry(QRect(300, 170, 100, 30));
        _marchingCubesIsoLevelSpinBox->setDecimals(3);
        _marchingCubesIsoLevelSpinBox->setMinimum(0.001);
        _marchingCubesIsoLevelSpinBox->setMaximum(1);
        _marchingCubesIsoLevelSpinBox->setSingleStep(0.001);
        _marchingCubesIsoLevelSpinBox->setValue(0.001);
        _marchingCubesNormalSearchRadiusLabel = new QLabel(_marchingCubesTab);
        _marchingCubesNormalSearchRadiusLabel->setObjectName(QStringLiteral("_marchingCubesNormalSearchRadiusLabel"));
        _marchingCubesNormalSearchRadiusLabel->setGeometry(QRect(10, 220, 250, 30));
        _marchingCubesNormalSearchRadiusSpinBox = new QDoubleSpinBox(_marchingCubesTab);
        _marchingCubesNormalSearchRadiusSpinBox->setObjectName(QStringLiteral("_marchingCubesNormalSearchRadiusSpinBox"));
        _marchingCubesNormalSearchRadiusSpinBox->setGeometry(QRect(300, 220, 100, 30));
        _marchingCubesNormalSearchRadiusSpinBox->setDecimals(3);
        _marchingCubesNormalSearchRadiusSpinBox->setMinimum(0.01);
        _marchingCubesNormalSearchRadiusSpinBox->setMaximum(1);
        _marchingCubesNormalSearchRadiusSpinBox->setSingleStep(0.01);
        _marchingCubesNormalSearchRadiusSpinBox->setValue(0.01);
        _reconstructTabWidget->addTab(_marchingCubesTab, QString());
        _reconstructProcessingButton = new QPushButton(_reconstructTab);
        _reconstructProcessingButton->setObjectName(QStringLiteral("_reconstructProcessingButton"));
        _reconstructProcessingButton->setGeometry(QRect(20, 420, 150, 40));
        _reconstructProcessingButton->setFont(font1);
        _processingTabWidget->addTab(_reconstructTab, QString());
        MainWindowForm->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindowForm);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1280, 21));
        menuCamera = new QMenu(menuBar);
        menuCamera->setObjectName(QStringLiteral("menuCamera"));
        menuPico_Flexx = new QMenu(menuCamera);
        menuPico_Flexx->setObjectName(QStringLiteral("menuPico_Flexx"));
        menuIntel_Realsense = new QMenu(menuCamera);
        menuIntel_Realsense->setObjectName(QStringLiteral("menuIntel_Realsense"));
        menuArduino = new QMenu(menuBar);
        menuArduino->setObjectName(QStringLiteral("menuArduino"));
        menucommunicate = new QMenu(menuArduino);
        menucommunicate->setObjectName(QStringLiteral("menucommunicate"));
        menuControl_Motor = new QMenu(menuArduino);
        menuControl_Motor->setObjectName(QStringLiteral("menuControl_Motor"));
        menuFile = new QMenu(menuBar);
        menuFile->setObjectName(QStringLiteral("menuFile"));
        menuPointCloud = new QMenu(menuBar);
        menuPointCloud->setObjectName(QStringLiteral("menuPointCloud"));
        menuKeep_PointCloud = new QMenu(menuPointCloud);
        menuKeep_PointCloud->setObjectName(QStringLiteral("menuKeep_PointCloud"));
        menuScan = new QMenu(menuBar);
        menuScan->setObjectName(QStringLiteral("menuScan"));
        MainWindowForm->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindowForm);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        MainWindowForm->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindowForm);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindowForm->setStatusBar(statusBar);

        menuBar->addAction(menuFile->menuAction());
        menuBar->addAction(menuCamera->menuAction());
        menuBar->addAction(menuArduino->menuAction());
        menuBar->addAction(menuPointCloud->menuAction());
        menuBar->addAction(menuScan->menuAction());
        menuCamera->addAction(menuPico_Flexx->menuAction());
        menuCamera->addAction(menuIntel_Realsense->menuAction());
        menuPico_Flexx->addAction(_startFlexxAction);
        menuPico_Flexx->addAction(_stopFlexxAction);
        menuPico_Flexx->addAction(_setConfidenceAction);
        menuIntel_Realsense->addAction(_startRSAction);
        menuIntel_Realsense->addAction(_stopRSAction);
        menuArduino->addAction(menucommunicate->menuAction());
        menuArduino->addAction(menuControl_Motor->menuAction());
        menucommunicate->addAction(_getNumberOfBytesAction);
        menucommunicate->addAction(_getCharAction);
        menucommunicate->addAction(_getArrayAction);
        menuControl_Motor->addAction(_controlMotorAction);
        menuFile->addAction(_openFileAction);
        menuFile->addAction(_saveFileAction);
        menuPointCloud->addAction(menuKeep_PointCloud->menuAction());
        menuKeep_PointCloud->addAction(_keepOneFrameAction);
        menuKeep_PointCloud->addAction(_keepContinueFrameAction);
        menuScan->addAction(_autoScanAction);

        retranslateUi(MainWindowForm);

        _processingTabWidget->setCurrentIndex(0);
        _filterTabWidget->setCurrentIndex(0);
        _keypointTabWidget->setCurrentIndex(0);
        _correspondencesTabWidget->setCurrentIndex(0);
        _regestrationTabWidget->setCurrentIndex(0);
        _reconstructTabWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(MainWindowForm);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindowForm)
    {
        MainWindowForm->setWindowTitle(QApplication::translate("MainWindowForm", "MainWindow", Q_NULLPTR));
        _startFlexxAction->setText(QApplication::translate("MainWindowForm", "Open", Q_NULLPTR));
        _stopFlexxAction->setText(QApplication::translate("MainWindowForm", "Close", Q_NULLPTR));
        _startRSAction->setText(QApplication::translate("MainWindowForm", "Open", Q_NULLPTR));
        _stopRSAction->setText(QApplication::translate("MainWindowForm", "Close", Q_NULLPTR));
        _getNumberOfBytesAction->setText(QApplication::translate("MainWindowForm", "Get # Bytes Of Data", Q_NULLPTR));
        _getCharAction->setText(QApplication::translate("MainWindowForm", "Get Char", Q_NULLPTR));
        _getArrayAction->setText(QApplication::translate("MainWindowForm", "Get Array", Q_NULLPTR));
        _controlMotorAction->setText(QApplication::translate("MainWindowForm", "Control Motor", Q_NULLPTR));
        _setConfidenceAction->setText(QApplication::translate("MainWindowForm", "Set Confidence", Q_NULLPTR));
        _IterativeClosestPointAction->setText(QApplication::translate("MainWindowForm", "PCL IterativeClosestPoint", Q_NULLPTR));
        _openFileAction->setText(QApplication::translate("MainWindowForm", "Open File", Q_NULLPTR));
        _saveFileAction->setText(QApplication::translate("MainWindowForm", "Save File", Q_NULLPTR));
        _keepOneFrameAction->setText(QApplication::translate("MainWindowForm", "One Frame", Q_NULLPTR));
        _keepContinueFrameAction->setText(QApplication::translate("MainWindowForm", "Continue Frame", Q_NULLPTR));
        actionFeature->setText(QApplication::translate("MainWindowForm", "Feature", Q_NULLPTR));
        _autoScanAction->setText(QApplication::translate("MainWindowForm", "Auto Scan", Q_NULLPTR));
        _voxelGridXLabel->setText(QApplication::translate("MainWindowForm", "X\357\274\232", Q_NULLPTR));
        _voxelGridYLabel->setText(QApplication::translate("MainWindowForm", "Y\357\274\232", Q_NULLPTR));
        _voxelGridZLabel->setText(QApplication::translate("MainWindowForm", "Z\357\274\232", Q_NULLPTR));
        _filterTabWidget->setTabText(_filterTabWidget->indexOf(_voxelGridTab), QApplication::translate("MainWindowForm", "Voxel Grid", Q_NULLPTR));
        _boundingBoxZLabel->setText(QApplication::translate("MainWindowForm", "Z\357\274\232", Q_NULLPTR));
        _boundingBoxXLabel->setText(QApplication::translate("MainWindowForm", "X\357\274\232", Q_NULLPTR));
        _boundingBoxYLabel->setText(QApplication::translate("MainWindowForm", "Y\357\274\232", Q_NULLPTR));
        _boundingBoxXShiftLabel->setText(QApplication::translate("MainWindowForm", "~", Q_NULLPTR));
        _boundingBoxYShiftLabel->setText(QApplication::translate("MainWindowForm", "~", Q_NULLPTR));
        _boundingBoxZShiftLabel->setText(QApplication::translate("MainWindowForm", "~", Q_NULLPTR));
        _filterTabWidget->setTabText(_filterTabWidget->indexOf(_boundingBoxTab), QApplication::translate("MainWindowForm", "Bounding Box", Q_NULLPTR));
        _filterProcessingButton->setText(QApplication::translate("MainWindowForm", "Processing", Q_NULLPTR));
        _processingTabWidget->setTabText(_processingTabWidget->indexOf(_filterTab), QApplication::translate("MainWindowForm", "Filter", Q_NULLPTR));
        _siftMinScaleLabel->setText(QApplication::translate("MainWindowForm", "Min Scale\357\274\232", Q_NULLPTR));
        _siftNROctavesLabel->setText(QApplication::translate("MainWindowForm", "NR Octaves\357\274\232", Q_NULLPTR));
        _siftNRScalesPerOctaveLabel->setText(QApplication::translate("MainWindowForm", "NR Scales Per Octave\357\274\232", Q_NULLPTR));
        _siftMinContrastLabel->setText(QApplication::translate("MainWindowForm", "Min Contrast\357\274\232", Q_NULLPTR));
        _keypointTabWidget->setTabText(_keypointTabWidget->indexOf(_sift3DTab), QApplication::translate("MainWindowForm", "SIFT3D", Q_NULLPTR));
        _harrisSetRadiusSearchLabel->setText(QApplication::translate("MainWindowForm", "Set Radius Search\357\274\232", Q_NULLPTR));
        _harrisRadiusLabel->setText(QApplication::translate("MainWindowForm", "Set Radius\357\274\232", Q_NULLPTR));
        _harrisMethodLabel->setText(QApplication::translate("MainWindowForm", "Method\357\274\232", Q_NULLPTR));
        _harrisMethodComboBox->clear();
        _harrisMethodComboBox->insertItems(0, QStringList()
         << QApplication::translate("MainWindowForm", "Harris3D", Q_NULLPTR)
         << QApplication::translate("MainWindowForm", "Tomasi3D", Q_NULLPTR)
         << QApplication::translate("MainWindowForm", "Noble3D", Q_NULLPTR)
         << QApplication::translate("MainWindowForm", "Lowe3D", Q_NULLPTR)
         << QApplication::translate("MainWindowForm", "Curvature3D", Q_NULLPTR)
        );
        _keypointTabWidget->setTabText(_keypointTabWidget->indexOf(_harris3DTab), QApplication::translate("MainWindowForm", "Harris3D", Q_NULLPTR));
        _keypointProcessingButton->setText(QApplication::translate("MainWindowForm", "Processing", Q_NULLPTR));
        _processingTabWidget->setTabText(_processingTabWidget->indexOf(_keypointTab), QApplication::translate("MainWindowForm", "Keypoint", Q_NULLPTR));
        _fpfhNormalRadiusLabel->setText(QApplication::translate("MainWindowForm", "Normal Radius\357\274\232", Q_NULLPTR));
        _fpfhdescriptorRadiusLabel->setText(QApplication::translate("MainWindowForm", "Descriptor Radius\357\274\232", Q_NULLPTR));
        _fpfhCorrespondencesKLabel->setText(QApplication::translate("MainWindowForm", "Correspondences K\357\274\232", Q_NULLPTR));
        _fpfhRejectorInlierThresholdLabel->setText(QApplication::translate("MainWindowForm", "Rejector Inlier Threshold\357\274\232", Q_NULLPTR));
        _correspondencesTabWidget->setTabText(_correspondencesTabWidget->indexOf(_fpfhTab), QApplication::translate("MainWindowForm", "FPFH", Q_NULLPTR));
        _shotdescriptorRadiusLabel->setText(QApplication::translate("MainWindowForm", "Descriptor Radius\357\274\232", Q_NULLPTR));
        _shotNormalRadiusLabel->setText(QApplication::translate("MainWindowForm", "Normal Radius\357\274\232", Q_NULLPTR));
        _shotCorrespondencesKLabel->setText(QApplication::translate("MainWindowForm", "Correspondences K\357\274\232", Q_NULLPTR));
        _shotRejectorInlierThresholdLabel->setText(QApplication::translate("MainWindowForm", "Rejector Inlier Threshold\357\274\232", Q_NULLPTR));
        _correspondencesTabWidget->setTabText(_correspondencesTabWidget->indexOf(_shotRGBTab), QApplication::translate("MainWindowForm", "SHOTRGB", Q_NULLPTR));
        _pfhdescriptorKSearchLabel->setText(QApplication::translate("MainWindowForm", "K Search\357\274\232", Q_NULLPTR));
        _pfhNormalRadiusLabel->setText(QApplication::translate("MainWindowForm", "Normal Radius\357\274\232", Q_NULLPTR));
        _pfhCorrespondencesKLabel->setText(QApplication::translate("MainWindowForm", "Correspondences K\357\274\232", Q_NULLPTR));
        _pfhRejectorInlierThresholdLabel->setText(QApplication::translate("MainWindowForm", "Rejector Inlier Threshold\357\274\232", Q_NULLPTR));
        _correspondencesTabWidget->setTabText(_correspondencesTabWidget->indexOf(_pfhTab), QApplication::translate("MainWindowForm", "PFH", Q_NULLPTR));
        _pfhrgbRejectorInlierThresholdLabel->setText(QApplication::translate("MainWindowForm", "Rejector Inlier Threshold\357\274\232", Q_NULLPTR));
        _pfhrgbCorrespondencesKLabel->setText(QApplication::translate("MainWindowForm", "Correspondences K\357\274\232", Q_NULLPTR));
        _pfhrgbdescriptorKSearchLabel->setText(QApplication::translate("MainWindowForm", "K Search\357\274\232", Q_NULLPTR));
        _pfhrgbNormalRadiusLabel->setText(QApplication::translate("MainWindowForm", "Normal Radius\357\274\232", Q_NULLPTR));
        _correspondencesTabWidget->setTabText(_correspondencesTabWidget->indexOf(_pfhrgbTab), QApplication::translate("MainWindowForm", "PFHRGB", Q_NULLPTR));
        _correspondencesProcessingButton->setText(QApplication::translate("MainWindowForm", "Processing", Q_NULLPTR));
        _processingTabWidget->setTabText(_processingTabWidget->indexOf(_correspondencesTab), QApplication::translate("MainWindowForm", "Correspondences", Q_NULLPTR));
        _regestrationProcessingButton->setText(QApplication::translate("MainWindowForm", "Processing", Q_NULLPTR));
        _icpOutlierThresholdLabel->setText(QApplication::translate("MainWindowForm", "Outlier Threshold\357\274\232", Q_NULLPTR));
        _icpCorrespondenceDistanceLabel->setText(QApplication::translate("MainWindowForm", "Correspondence Distance\357\274\232", Q_NULLPTR));
        _icpTransformationEpsilonLabel->setText(QApplication::translate("MainWindowForm", "Transformation Epsilon\357\274\232", Q_NULLPTR));
        _icpMaxIterationsLabel->setText(QApplication::translate("MainWindowForm", "Max Iterations\357\274\232", Q_NULLPTR));
        _regestrationTabWidget->setTabText(_regestrationTabWidget->indexOf(_icpTab), QApplication::translate("MainWindowForm", "ICP", Q_NULLPTR));
        _processingTabWidget->setTabText(_processingTabWidget->indexOf(_regestrationTab), QApplication::translate("MainWindowForm", "Regestration", Q_NULLPTR));
        _greedyProjectionMuLabel->setText(QApplication::translate("MainWindowForm", "Mu\357\274\232", Q_NULLPTR));
        _greedyProjectionSearchRadiusLabel->setText(QApplication::translate("MainWindowForm", "Search Radius\357\274\232", Q_NULLPTR));
        _greedyProjectionMaxNearestNeighborsLabel->setText(QApplication::translate("MainWindowForm", "Max Nearest Neighbors\357\274\232", Q_NULLPTR));
        _greedyProjectionMaxSurfaceAngleLabel->setText(QApplication::translate("MainWindowForm", "Max Surface Angle\357\274\232", Q_NULLPTR));
        _greedyProjectionMinAngleLabel->setText(QApplication::translate("MainWindowForm", "Min Angle\357\274\232", Q_NULLPTR));
        _greedyProjectionMaxAngleLabel->setText(QApplication::translate("MainWindowForm", "Max Angle\357\274\232", Q_NULLPTR));
        _GreedyProjectNormalSearchRadiusLabel->setText(QApplication::translate("MainWindowForm", "Normal Search Radius\357\274\232", Q_NULLPTR));
        _reconstructTabWidget->setTabText(_reconstructTabWidget->indexOf(_greedyProjectionTab), QApplication::translate("MainWindowForm", "Greedy Projection", Q_NULLPTR));
        _marchingCubesGridResolutionXLabel->setText(QApplication::translate("MainWindowForm", "Grid Resolution X\357\274\232", Q_NULLPTR));
        _marchingCubesGridResolutionZLabel->setText(QApplication::translate("MainWindowForm", "Grid Resolution \357\274\272\357\274\232", Q_NULLPTR));
        _marchingCubesGridResolutionYLabel->setText(QApplication::translate("MainWindowForm", "Grid Resolution \357\274\271\357\274\232", Q_NULLPTR));
        _marchingCubesIsoLevelLabel->setText(QApplication::translate("MainWindowForm", "Iso Level\357\274\232", Q_NULLPTR));
        _marchingCubesNormalSearchRadiusLabel->setText(QApplication::translate("MainWindowForm", "Normal Search Radius\357\274\232", Q_NULLPTR));
        _reconstructTabWidget->setTabText(_reconstructTabWidget->indexOf(_marchingCubesTab), QApplication::translate("MainWindowForm", "Marching Cubes", Q_NULLPTR));
        _reconstructProcessingButton->setText(QApplication::translate("MainWindowForm", "Processing", Q_NULLPTR));
        _processingTabWidget->setTabText(_processingTabWidget->indexOf(_reconstructTab), QApplication::translate("MainWindowForm", "Reconstruct", Q_NULLPTR));
        menuCamera->setTitle(QApplication::translate("MainWindowForm", "Camera", Q_NULLPTR));
        menuPico_Flexx->setTitle(QApplication::translate("MainWindowForm", "Pico Flexx", Q_NULLPTR));
        menuIntel_Realsense->setTitle(QApplication::translate("MainWindowForm", "Intel Realsense", Q_NULLPTR));
        menuArduino->setTitle(QApplication::translate("MainWindowForm", "Arduino", Q_NULLPTR));
        menucommunicate->setTitle(QApplication::translate("MainWindowForm", "Communicate", Q_NULLPTR));
        menuControl_Motor->setTitle(QApplication::translate("MainWindowForm", "Control Motor", Q_NULLPTR));
        menuFile->setTitle(QApplication::translate("MainWindowForm", "File", Q_NULLPTR));
        menuPointCloud->setTitle(QApplication::translate("MainWindowForm", "PointClouds", Q_NULLPTR));
        menuKeep_PointCloud->setTitle(QApplication::translate("MainWindowForm", "Keep PointCloud", Q_NULLPTR));
        menuScan->setTitle(QApplication::translate("MainWindowForm", "Scan", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class MainWindowForm: public Ui_MainWindowForm {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
